### PR TITLE
Remove default BLACKLIST

### PR DESCRIPTION
**Pull request by lynchbomb**

### CODE REVIEW

**Comment by scalvert** [comment]
Why did we do this, out of curiosity?

**Comment by lynchbomb** [comment]
TL;DR its unnecessary and doesn't cover valid use-cases. The intent is the variable jQuery methods flagged into a blacklist should to be provided by the consuming application.

The existing `BLACKLIST` was only a sub-set of jQuery methods from a specific version of jQuery (v2.1.4). Since consuming applications will be on varying versions we shouldn't default a set or sub-set of methods as we won't cover all use-cases.

**Comment by lynchbomb** [comment]
@trentmwillis Agreed. I'll include a comment regarding usage.

**Comment by lynchbomb** [comment]
Good to go. Merge away!

**Pull request merged**
